import { Link, useLocation } from "react-router-dom";
import { SEO } from "@/components/SEO";
import SiteShell from "@/components/SiteShell";
import Breadcrumbs from "@/components/Breadcrumbs";
import QuoteDialog from "@/components/QuoteDialog";
import { blogTemplates } from "@/data/siteContent";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

const content: Record<string, { intro: string; sections: [string, string][] }> = {
  "solar-panel-price-bangladesh": { intro: "Solar quotations differ because equipment, design and site scope differ. Compare complete systems rather than panel wattage alone.", sections: [["What determines a solar quote?", "Capacity, panel and inverter specifications, mounting, protection, cable routes, battery choice, roof work, monitoring and installation access all influence cost."], ["How should buyers compare proposals?", "Check equipment model numbers, warranties, included protection, mounting material, expected output assumptions, exclusions, after-sales support and payment terms."], ["Which prices are currently stated?", "BD Solar Power currently states a 5kW system from BDT 275,000, subject to survey and final scope. Request current pricing for other sizes."]] },
  "5kw-solar-system-bangladesh": { intro: "A 5kW system can be a useful pathway for family homes and some smaller commercial properties, but only after load and roof review.", sections: [["Who may suit a 5kW system?", "Properties with meaningful daytime loads, sufficient unshaded roof and electrical conditions suitable for the proposed design may consider this size."], ["How much roof area is needed?", "Module dimensions, spacing, access paths, orientation and shading determine the actual area. Confirm it in a rooftop survey rather than relying on a generic figure."], ["What does a 5kW system cost?", "The currently stated starting price is BDT 275,000. Batteries, roof work, equipment choices and electrical scope can change the final total."]] },
  "net-metering-bangladesh-guide": { intro: "Net metering may help eligible consumers account for surplus rooftop solar exports, but applications and bill treatment follow current utility rules.", sections: [["How does net metering work?", "A suitable meter records grid imports and eligible exports. Your utility applies the current rules to the billing period."], ["What should an applicant prepare?", "Prepare a recent bill, identification, ownership or occupancy evidence and proposed technical details. Confirm the exact checklist with the distribution utility."], ["What can delay approval?", "Incomplete documents, unsuitable capacity, electrical issues, inspection findings, meter availability and policy changes can affect timing."]] },
  "grid-tied-vs-hybrid-solar-bangladesh": { intro: "Choose system architecture based on whether your priority is daytime bill offset, outage backup or a combination of both.", sections: [["What is grid-tied solar?", "Grid-tied systems work with the utility supply and normally shut down during outages for safety. They often focus on daytime energy offset."], ["What is hybrid solar?", "Hybrid systems can coordinate solar, grid and batteries. Backup capacity depends on battery storage, inverter capability and selected circuits."], ["Which option costs more?", "Battery-backed designs usually cost more and require additional maintenance and replacement planning. Compare lifecycle scope, not only purchase price."]] },
  "solar-panel-maintenance-bangladesh": { intro: "Dust, leaves, bird droppings, moisture and shading can affect rooftop systems, so regular visual and electrical checks matter.", sections: [["How often should panels be cleaned?", "Cleaning frequency depends on dust, rainfall, roof access and measured performance. Follow safe methods and avoid walking on modules."], ["What should be inspected?", "Check visible damage, loose cables, mounting, earthing, protection equipment, inverter alerts and monitoring trends. Qualified personnel should handle electrical work."], ["How can owners spot a problem?", "Unexpected production drops, repeated inverter faults, overheating, damaged wiring or water ingress should prompt an inspection."]] },
  "how-to-reduce-electricity-bill-bangladesh": { intro: "Rooftop solar may reduce grid purchases when generation aligns with your loads, but savings depend on design and usage.", sections: [["Which loads should be reviewed first?", "List daytime air conditioning, pumps, refrigeration, machinery, lighting and other recurring loads alongside monthly consumption."], ["Why does self-consumption matter?", "Using solar electricity as it is generated can reduce imports. Export treatment depends on net-metering eligibility and current rules."], ["What else improves the result?", "Energy efficiency, shading control, suitable orientation, quality installation and monitoring can support better performance."]] },
};
export default function BlogGuide() { const { pathname } = useLocation(); const slug = pathname.split("/").filter(Boolean).slice(-1)[0]; const meta = blogTemplates.find((item) => item.slug === slug); const article = slug ? content[slug] : undefined; if (!meta || !article) return null; return <SiteShell><SEO title={meta.title} description={article.intro} canonicalUrl={`https://bdsolarpower.com/blog/${meta.slug}`} type="article" publishedTime="2026-09-20T00:00:00Z" modifiedTime="2026-09-20T00:00:00Z" author="BD Solar Expert Team" articleHeadline={meta.title} /><article className="mx-auto max-w-4xl px-4 py-12 sm:px-6"><Breadcrumbs current={meta.title} parent={{ label: "Blog", path: "/blog" }} /><Badge className="mt-8">{meta.category}</Badge><h1 className="mt-4 text-4xl font-bold leading-tight sm:text-5xl">{meta.title}</h1><p className="mt-6 text-xl leading-8 text-muted-foreground">{article.intro}</p><div className="mt-10 space-y-10">{article.sections.map(([heading, text]) => <section key={heading}><h2 className="text-2xl font-bold">{heading}</h2><p className="mt-4 leading-8 text-muted-foreground">{text}</p></section>)}</div><div className="mt-12 rounded-xl border bg-muted p-6"><h2 className="text-2xl font-bold">What should you do next?</h2><p className="mt-3 text-muted-foreground">Use a site-specific assessment before making a purchase decision.</p><div className="mt-5 flex flex-wrap gap-3"><QuoteDialog /><Button asChild variant="outline"><Link to="/solar-system-price-bangladesh">Compare system sizes</Link></Button></div></div></article></SiteShell>; }
