import { useLocation } from "react-router-dom";
import { Building2, CheckCircle2, ClipboardCheck, FileCheck2, MapPin, ShieldCheck } from "lucide-react";
import { SEO } from "@/components/SEO";
import SiteShell from "@/components/SiteShell";
import Breadcrumbs from "@/components/Breadcrumbs";
import FAQList from "@/components/FAQList";
import QuoteDialog from "@/components/QuoteDialog";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { commercialSectors, locations, policyNotice, solarSystems } from "@/data/siteContent";

type Page = { title: string; description: string; intro: string; sections: { heading: string; text: string }[]; faq?: readonly (readonly [string, string])[] };
const simpleFaq = [["How does the process start?", "Share your electricity bill, property type and roof details. A site assessment is required before final design or pricing."], ["Are savings guaranteed?", "No. Generation and savings vary with site conditions, usage, equipment, tariffs and approvals."], ["Is net metering included?", "Documentation guidance can be included where applicable, but eligibility and approval remain subject to current utility requirements."]] as const;
const pages: Record<string, Page> = {
  "/net-metering-bangladesh": { title: "Net Metering in Bangladesh: A Practical Rooftop Solar Guide", description: "Understand rooftop solar net-metering eligibility, documents, approvals and bill impacts in Bangladesh.", intro: "Eligible consumers may offset electricity usage and, where permitted, export surplus solar power to the grid. Rules and tariff treatment can change, so get a personalized assessment before deciding.", sections: [{ heading: "What does net metering mean?", text: "A suitable meter records electricity imported from the grid and eligible surplus electricity exported by the solar system. The bill treatment follows the applicable utility rules." }, { heading: "Who may be eligible?", text: "Eligibility depends on consumer category, sanctioned load, roof and electrical condition, proposed capacity and the current requirements of the relevant distribution utility." }, { heading: "Which documents and approvals may be required?", text: "A current electricity bill, ownership or occupancy evidence, identification, system design, equipment details and technical inspection may be requested. The exact checklist should be confirmed with the utility." }, { heading: "What is the usual application process?", text: "Site assessment, preliminary design, utility application, technical review, installation, inspection, metering and commissioning may form part of the journey. Sequence and timing vary." }, { heading: "How can net metering affect the bill?", text: "A properly sized system may offset some imported electricity and receive the treatment permitted for eligible exports. Usage patterns, generation and current tariff rules determine the outcome." }, { heading: "What should buyers verify about incentives?", text: `${policyNotice.text} ${policyNotice.disclaimer} Last reviewed: ${policyNotice.lastReviewed}.` }], faq: simpleFaq },
  "/residential-solar-bangladesh": { title: "Residential Solar Systems for Homes in Bangladesh", description: "Compare grid-tied, hybrid and battery-backed rooftop solar for homes, apartments and villas in Bangladesh.", intro: "Residential solar should be sized around your real electricity use, suitable roof area and backup priorities—not a one-size package.", sections: [{ heading: "Which homes can consider rooftop solar?", text: "Homes, villas and suitable apartment buildings can be assessed for 1kW, 3kW, 5kW or 10kW pathways based on loads, roof access and ownership approvals." }, { heading: "Grid-tied, hybrid or battery-backed?", text: "Grid-tied systems focus on daytime offset. Hybrid systems can coordinate solar, grid and batteries. Battery capacity should be selected around essential or full-backup loads." }, { heading: "How are bills, maintenance and warranties handled?", text: "Savings vary with consumption and site conditions. Panels need periodic cleaning and system checks. The current offer states a 25-year panel warranty; final terms depend on selected equipment." }], faq: simpleFaq },
  "/commercial-solar-bangladesh": { title: "Commercial Solar Installation in Bangladesh", description: "Engineer-reviewed rooftop solar for factories, offices, schools, hospitals, warehouses and hotels in Bangladesh.", intro: "Commercial solar requires load data, structural review, safety planning and a site-specific financial proposal.", sections: commercialSectors.map((sector) => ({ heading: `How can solar support ${sector.label.toLowerCase()}?`, text: `${sector.pain} BD Solar Power develops a custom recommendation after reviewing bills, operating hours and the site.` })), faq: simpleFaq },
  "/about": { title: "About BD Solar Power", description: "Learn about BD Solar Power's approach to rooftop surveys, system design, installation and support across Bangladesh.", intro: "BD Solar Power helps homes and businesses evaluate, design and install rooftop solar systems with clear assumptions and site-specific recommendations.", sections: [{ heading: "What is our mission?", text: "Make rooftop solar easier to understand and evaluate for Bangladesh properties through practical surveys, clear proposals and responsible guidance." }, { heading: "How do we approach engineering?", text: "We begin with bills, roof details and goals, then assess structure, shading, electrical conditions, safety and applicable utility requirements." }, { heading: "Where do we work?", text: "Service is offered across Bangladesh, subject to assessment and scheduling. The verified business location currently published is Mymensingh." }, { heading: "Which credentials can buyers review?", text: "Verified certificates and team credentials will be published here when supplied. No government affiliation or certification is claimed without documentation." }], faq: simpleFaq },
  "/contact": { title: "Get a Solar Quote in Bangladesh", description: "Request a free rooftop solar site survey in Bangladesh and share your electricity bill and property details.", intro: "Send your latest electricity bill and rooftop details for an initial recommendation. Service availability is confirmed after assessment.", sections: [{ heading: "What happens after a quote request?", text: "The solar team reviews your location, property type, bill and system goals, then contacts you to arrange the next appropriate step." }, { heading: "What should you prepare for a free survey?", text: "Keep a recent electricity bill, roof photos, location and notes about daytime loads or backup needs ready." }], faq: simpleFaq },
  "/privacy": { title: "Privacy Policy", description: "Learn how BD Solar Power collects, uses and protects information submitted through this website.", intro: "This policy explains what information BD Solar Power receives when you use the website or request a solar quote, and how that information is handled.", sections: [{ heading: "What information do we collect?", text: "We may collect the details you choose to submit, including your name, phone number, email, company, location, property details, electricity usage and message. Basic website usage data may also be collected through analytics." }, { heading: "How do we use your information?", text: "Submitted information is used to respond to enquiries, assess solar requirements, arrange surveys, prepare proposals, provide support and improve the website. We do not sell your personal information." }, { heading: "Who may receive your information?", text: "Information may be shared with service providers that help operate the website or deliver requested services, only where reasonably necessary. Information may also be disclosed when required by law." }, { heading: "How long is information kept?", text: "Information is retained only as long as reasonably needed for enquiries, customer service, legal obligations and legitimate business records. Reasonable safeguards are used, but no online system can guarantee absolute security." }, { heading: "How can you contact us about privacy?", text: `To ask about, correct or request deletion of information you submitted, email ${business.email}. Requests may be subject to identity verification and applicable legal requirements.` }] },
  "/terms": { title: "Website Terms", description: "Read the terms for using the BD Solar Power website, calculators, guides and quote request services.", intro: "These terms apply when you use the BD Solar Power website, its information, calculators and enquiry services.", sections: [{ heading: "How may this website be used?", text: "You may use this website for lawful personal or business research and to request solar services. You must not misuse the website, attempt unauthorized access or submit false, harmful or unlawful content." }, { heading: "Are prices and estimates final offers?", text: "No. Published prices, generation figures, savings, payback periods and calculator results are general estimates. Final scope, price, performance and timing require site assessment, engineering review and a written proposal." }, { heading: "What applies to incentives and net metering?", text: "Incentives, tariffs, financing and net-metering eligibility depend on current rules, utility approval, customer category and site conditions. Website guidance does not guarantee approval or a particular bill outcome." }, { heading: "Who owns the website content?", text: "Unless otherwise stated, BD Solar Power owns or is licensed to use the website text, design and original materials. Content may not be republished commercially without permission." }, { heading: "How can questions about these terms be raised?", text: `Questions about these terms can be sent to ${business.email}. BD Solar Power may update these terms when services or legal requirements change.` }] },
};

export default function MarketingPage() {
  const { pathname } = useLocation();
  const sector = commercialSectors.find((item) => pathname === `/${item.slug}-solar-bangladesh`);
  const location = locations.find((item) => item.path === pathname);
  const page = pages[pathname] ?? (sector ? { title: sector.title, description: `Custom rooftop solar assessment for ${sector.label.toLowerCase()} in Bangladesh.`, intro: sector.pain, sections: [{ heading: "What does a tailored project include?", text: "The process can include bill and load analysis, site and structural review, concept design, safety planning, proposal, installation, testing and applicable utility guidance." }, { heading: "Why is an engineering assessment required?", text: "Commercial loads, roof structures, operating schedules and electrical systems differ. Final capacity, equipment, savings and timeline must follow site-specific engineering." }], faq: simpleFaq } : location ? { title: `Solar Installation in ${location.name}`, description: `Residential and commercial rooftop solar surveys and installation guidance in ${location.name}, Bangladesh.`, intro: `Homes and businesses in ${location.name} can request a rooftop assessment for solar sizing, installation and applicable net-metering guidance.`, sections: [{ heading: `Which solar services are available in ${location.name}?`, text: "Residential and commercial assessments cover bill review, roof suitability, system pathways, backup needs and installation scope." }, { heading: "How do I schedule a local survey?", text: "Submit your city, property type, latest bill and roof details. Availability is confirmed after the initial assessment." }, { heading: "Is there a local office?", text: "No local office address is claimed on this page. Service is scheduled based on project location and assessment." }, { heading: "Where is the map?", text: "A verified map location can be added when a local office or project point is approved for publication." }], faq: simpleFaq } : pages["/about"]);
  const faqSchema = page.faq ? { "@type": "FAQPage", mainEntity: page.faq.map(([q, a]) => ({ "@type": "Question", name: q, acceptedAnswer: { "@type": "Answer", text: a } })) } : undefined;
  return <SiteShell><SEO title={page.title} description={page.description} canonicalUrl={`https://bdsolarpower.com${pathname}`} faqSchema={faqSchema} /><div className="border-b bg-muted/50"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6"><Breadcrumbs current={page.title} /><div className="mt-8 max-w-4xl"><p className="font-semibold text-primary">Rooftop solar in Bangladesh</p><h1 className="mt-3 text-4xl font-bold sm:text-5xl">{page.title}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-muted-foreground">{page.intro}</p><QuoteDialog size="lg" className="mt-7" /></div></div></div><div className="mx-auto grid max-w-7xl gap-6 px-4 py-16 sm:px-6 md:grid-cols-2">{page.sections.map((section, index) => { const Icon = [Building2, ClipboardCheck, ShieldCheck, FileCheck2, MapPin, CheckCircle2][index % 6]; return <Card key={section.heading}><CardHeader><Icon className="h-6 w-6 text-primary" /><CardTitle className="pt-2">{section.heading}</CardTitle></CardHeader><CardContent><p className="leading-7 text-muted-foreground">{section.text}</p></CardContent></Card>; })}</div>{page.faq && <FAQList items={page.faq} />}</SiteShell>;
}
