import { useEffect, useState } from "react";
import { SEO } from "@/components/SEO";
import SiteShell from "@/components/SiteShell";
import Breadcrumbs from "@/components/Breadcrumbs";
import QuoteDialog from "@/components/QuoteDialog";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { supabase } from "@/integrations/supabase/client";
import { MapPin } from "lucide-react";
type Project = { id: string; name: string; location: string; capacity_mw: number; status: string; description: string | null };
export default function Projects() { const [projects, setProjects] = useState<Project[]>([]); useEffect(() => { supabase.from("solar_projects").select("id,name,location,capacity_mw,status,description").order("created_at", { ascending: false }).then(({ data, error }) => { if (error) console.error("Could not load projects:", error); else setProjects(data ?? []); }); }, []); return <SiteShell><SEO title="Solar Projects in Bangladesh" description="Browse published solar project records across Bangladesh and request details or a site-specific rooftop solar assessment." canonicalUrl="https://bdsolarpower.com/solar-projects-bangladesh" /><div className="mx-auto max-w-7xl px-4 py-12 sm:px-6"><Breadcrumbs current="Solar Projects" /><div className="mt-8 max-w-4xl"><h1 className="text-4xl font-bold">Solar Projects in Bangladesh</h1><p className="mt-4 text-lg leading-8 text-muted-foreground">Explore published project records from the live project database. Capacity and status are displayed as recorded; images and case-study evidence are added only when verified.</p></div><div className="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{projects.map((project) => <Card key={project.id}><div className="grid aspect-video place-items-center rounded-t-xl bg-gradient-to-br from-emerald-100 to-amber-50"><MapPin className="h-10 w-10 text-primary" /></div><CardHeader><div className="flex justify-between gap-3"><CardTitle>{project.name}</CardTitle><Badge variant="secondary">{project.status.replace(/_/g, " ")}</Badge></div></CardHeader><CardContent><p className="text-sm text-muted-foreground">{project.location}</p><p className="mt-2 font-semibold">{project.capacity_mw < 1 ? `${project.capacity_mw * 1000} kW` : `${project.capacity_mw} MW`}</p>{project.description && <p className="mt-3 text-sm leading-6 text-muted-foreground">{project.description}</p>}</CardContent></Card>)}</div>{projects.length === 0 && <p className="mt-10 rounded-lg border bg-muted p-6 text-muted-foreground">Project records are being loaded. Request a survey to discuss a project for your property.</p>}<div className="mt-12 rounded-2xl bg-primary p-8 text-primary-foreground"><h2 className="text-3xl font-bold">Planning a similar project?</h2><p className="mt-3 text-primary-foreground/80">Request project details or arrange a survey for your own rooftop.</p><QuoteDialog label="Request Project Details" variant="secondary" size="lg" className="mt-6" /></div></div></SiteShell>; }
