import { Link, useLocation } from "react-router-dom";
import { SEO } from "@/components/SEO";
import SiteShell from "@/components/SiteShell";
import Breadcrumbs from "@/components/Breadcrumbs";
import FAQList from "@/components/FAQList";
import QuoteDialog from "@/components/QuoteDialog";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { solarSystems } from "@/data/siteContent";

const faqs = [["Is the displayed price final?", "No. Starting prices and ranges are planning references. Final cost depends on survey, design, equipment and scope."], ["Does the price include batteries?", "Battery inclusion depends on whether you choose grid-tied, hybrid or backup capability. The final quote lists included equipment."], ["How is the correct size selected?", "Review electricity bills, daytime loads, available roof, shading, sanctioned load and backup priorities before final sizing."], ["Can I apply for net metering?", "Eligibility depends on current utility rules and your property and connection details."]] as const;
export default function SolarPricing() {
  const { pathname } = useLocation(); const system = solarSystems.find((item) => item.path === pathname); const isHub = !system;
  const title = system ? `${system.size} Solar System Price in Bangladesh` : "Solar System Price in Bangladesh";
  const description = system ? `Plan a ${system.size} rooftop solar system in Bangladesh. Review use cases, cost drivers, roof needs and request a site-specific quote.` : "Compare 1kW, 3kW, 5kW and 10kW solar system pathways in Bangladesh and request a free site survey.";
  return <SiteShell><SEO title={title} description={description} canonicalUrl={`https://bdsolarpower.com${pathname}`} faqSchema={{ "@type": "FAQPage", mainEntity: faqs.map(([q, a]) => ({ "@type": "Question", name: q, acceptedAnswer: { "@type": "Answer", text: a } })) }} /><div className="mx-auto max-w-7xl px-4 py-12 sm:px-6"><Breadcrumbs current={title} /><div className="mt-8 max-w-4xl"><h1 className="text-4xl font-bold sm:text-5xl">{title}</h1><p className="mt-5 text-lg leading-8 text-muted-foreground">{system ? `${system.size} systems may suit ${system.bestFor.toLowerCase()}. ${system.useCases}` : "System cost depends on capacity, panel and inverter selection, mounting, protection, wiring, batteries, roof work and installation conditions."}</p></div>{system ? <><div className="mt-10 grid gap-6 md:grid-cols-3">{[["Current price guidance", system.price], ["Typical fit", system.bestFor], ["Roof guidance", system.roof]].map(([label, value]) => <Card key={label}><CardHeader><CardTitle className="text-base">{label}</CardTitle></CardHeader><CardContent className="font-semibold text-primary">{value}</CardContent></Card>)}</div><section className="mt-14 grid gap-8 lg:grid-cols-2"><div><h2 className="text-3xl font-bold">What drives the final {system.size} price?</h2><ul className="mt-5 list-disc space-y-3 pl-5 text-muted-foreground">{["Panel, inverter and mounting specifications", "Grid-tied, hybrid or battery-backed design", "Roof strength, access, shading and required civil work", "Cable routes, electrical protection and distribution-board work", "Monitoring, documentation and after-sales scope"].map((item) => <li key={item}>{item}</li>)}</ul></div><div><h2 className="text-3xl font-bold">What should the site survey confirm?</h2><p className="mt-5 leading-7 text-muted-foreground">The survey should check roof dimensions and condition, shading, electrical connection, major loads, preferred backup circuits, equipment locations and safe installation access.</p><QuoteDialog size="lg" className="mt-6" /></div></section><div className="mt-12 flex flex-wrap gap-3">{system.adjacent.map((link) => <Button key={link.path} asChild variant="outline"><Link to={link.path}>{link.label}</Link></Button>)}</div></> : <div className="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-4">{solarSystems.map((item) => <Card key={item.key}><CardHeader><CardTitle>{item.size}</CardTitle></CardHeader><CardContent><p className="font-semibold text-primary">{item.price}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{item.bestFor}</p><Button asChild variant="link" className="mt-4 px-0"><Link to={item.path}>View full guide →</Link></Button></CardContent></Card>)}</div>}</div><FAQList items={faqs} title={`What should you know about ${system?.size ?? "solar system"} pricing?`} /></SiteShell>;
}
