import { useMemo, useState } from "react";
import { SEO } from "@/components/SEO";
import SiteShell from "@/components/SiteShell";
import Breadcrumbs from "@/components/Breadcrumbs";
import QuoteDialog from "@/components/QuoteDialog";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export default function SolarCalculator() {
  const [bill, setBill] = useState("10000"); const [kwh, setKwh] = useState(""); const [roof, setRoof] = useState("500"); const [location, setLocation] = useState("Dhaka"); const [property, setProperty] = useState("Home"); const [backup, setBackup] = useState("None");
  const result = useMemo(() => { const monthly = Math.max(Number(bill) || 0, (Number(kwh) || 0) * 12); const roofLimit = (Number(roof) || 0) / 100; const base = Math.max(1, Math.min(100, monthly / 1800)); const size = Math.min(base, roofLimit || base); const low = Math.max(1, Math.floor(size * .8)); const high = Math.max(low + 1, Math.ceil(size * 1.2)); return { size: `${low}–${high} kW`, generation: `${Math.round(low * 1200).toLocaleString()}–${Math.round(high * 1500).toLocaleString()} kWh`, offset: "40–75%", payback: "Requires tariff and proposal review", area: `${Math.round(low * 90)}–${Math.round(high * 110)} sq ft` }; }, [bill, kwh, roof]);
  return <SiteShell><SEO title="Bangladesh Solar Savings Calculator" description="Estimate rooftop solar size, generation, roof area and bill offset in Bangladesh, then request an engineer-reviewed proposal." canonicalUrl="https://bdsolarpower.com/solar-calculator-bangladesh" /><div className="mx-auto max-w-7xl px-4 py-10 sm:px-6"><Breadcrumbs current="Solar Calculator" /><div className="mt-8 max-w-3xl"><h1 className="text-4xl font-bold">Bangladesh Solar Savings Calculator</h1><p className="mt-4 text-lg text-muted-foreground">Use a few property details to create an illustrative starting point for your site survey.</p></div><div className="mt-10 grid gap-8 lg:grid-cols-2"><Card><CardHeader><CardTitle>Your property</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><Field label="Monthly electricity bill (BDT)"><Input type="number" value={bill} onChange={(e) => setBill(e.target.value)} /></Field><Field label="Monthly consumption (kWh, optional)"><Input type="number" value={kwh} onChange={(e) => setKwh(e.target.value)} /></Field><Field label="Location"><Input value={location} onChange={(e) => setLocation(e.target.value)} /></Field><Field label="Available roof area (sq ft)"><Input type="number" value={roof} onChange={(e) => setRoof(e.target.value)} /></Field><Field label="Property type"><Select value={property} onValueChange={setProperty}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["Home", "Apartment", "Office", "Factory", "School", "Hospital"].map((v) => <SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></Field><Field label="Backup option"><Select value={backup} onValueChange={setBackup}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["None", "Essential loads", "Full backup"].map((v) => <SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></Field></CardContent></Card><div><div className="grid grid-cols-2 gap-4">{Object.entries({ "Suggested size": result.size, "Yearly generation": result.generation, "Potential bill offset": result.offset, "Indicative payback": result.payback, "Required roof area": result.area }).map(([label, value]) => <Card key={label}><CardContent className="p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 font-bold text-primary">{value}</p></CardContent></Card>)}</div><p className="mt-5 rounded-md border bg-muted p-4 text-sm leading-6 text-muted-foreground">Estimates are illustrative. Actual generation and financial outcomes depend on sunlight, shading, roof orientation, electricity tariff, system design, equipment, battery choice, use pattern, utility approvals and policy.</p><QuoteDialog label="Request an engineer-reviewed proposal" size="lg" className="mt-5 w-full" /></div></div></div></SiteShell>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
