import { Link } from "react-router-dom";
import { Mail, MessageCircle, Sun } from "lucide-react";
import { business, locations, solarSystems } from "@/data/siteContent";

const groups = [
  { title: "Solar systems", links: [...solarSystems.map((s) => ({ label: s.size, path: s.path })), { label: "Commercial", path: "/commercial-solar-bangladesh" }] },
  { title: "Guides", links: [{ label: "Net Metering", path: "/net-metering-bangladesh" }, { label: "Calculator", path: "/solar-calculator-bangladesh" }, { label: "Pricing", path: "/solar-system-price-bangladesh" }, { label: "Maintenance Blog", path: "/blog" }] },
  { title: "Locations", links: locations.map((l) => ({ label: l.name, path: l.path })) },
  { title: "Company", links: [{ label: "About", path: "/about" }, { label: "Projects", path: "/solar-projects-bangladesh" }, { label: "Contact", path: "/contact" }, { label: "Privacy Policy", path: "/privacy" }, { label: "Terms", path: "/terms" }] },
];
export default function Footer() { return <footer className="bg-foreground text-background"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6"><div className="grid gap-10 lg:grid-cols-[1.3fr_repeat(4,1fr)]"><div><Link to="/" className="flex items-center gap-2 font-bold"><Sun className="h-6 w-6 text-primary" />BD Solar Power</Link><p className="mt-4 max-w-xs text-sm leading-6 text-background/70">Rooftop solar installation, site surveys and net-metering guidance for homes and businesses across Bangladesh.</p><div className="mt-5 space-y-2 text-sm"><a href={`mailto:${business.email}`} className="flex items-center gap-2 hover:text-primary"><Mail className="h-4 w-4" />{business.email}</a><a href={`https://wa.me/${business.whatsapp}`} className="flex items-center gap-2 hover:text-primary"><MessageCircle className="h-4 w-4" />WhatsApp</a></div></div>{groups.map((group) => <div key={group.title}><h2 className="font-semibold">{group.title}</h2><ul className="mt-4 space-y-2">{group.links.map((link) => <li key={link.path + link.label}><Link to={link.path} className="text-sm text-background/70 hover:text-primary">{link.label}</Link></li>)}</ul></div>)}</div><div className="mt-10 border-t border-background/20 pt-6 text-xs leading-5 text-background/60"><p>© 2026 BD Solar Power. All rights reserved.</p><p className="mt-2">Information on this website is for general guidance. Pricing, system performance, savings, financing, incentives and net-metering eligibility are subject to site conditions and applicable rules.</p></div></div></footer>; }
