import React from "react";

interface BlogContentSection {
  heading: string;
  paragraphs: string[];
  list?: string[];
  table?: { headers: string[]; rows: string[][] };
  callout?: { title: string; text: string };
}

export interface BlogArticleContent {
  sections: BlogContentSection[];
}

export const blogPostContent: Record<string, BlogArticleContent> = {
  "1": {
    sections: [
      {
        heading: "Solar Panel Prices in Bangladesh: 2025 Overview",
        paragraphs: [
          "The solar panel market in Bangladesh has undergone a dramatic transformation in 2025, with prices dropping by approximately 36% compared to 2022. This reduction is driven by global manufacturing scale, reduced import duties (now just 1%), and growing domestic demand fueled by the government's 3,000 MW rooftop solar initiative.",
          "For homeowners and businesses considering solar, understanding the current pricing landscape is essential to making an informed investment decision."
        ]
      },
      {
        heading: "System Size and Price Breakdown",
        paragraphs: [
          "Here's what you can expect to pay for different solar system sizes in Bangladesh in 2025:"
        ],
        table: {
          headers: ["System Size", "Price Range (BDT)", "Monthly Savings", "Payback Period"],
          rows: [
            ["1 kW", "85,000 – 110,000", "~1,200", "5-6 years"],
            ["2 kW", "150,000 – 190,000", "~2,400", "4-5 years"],
            ["3 kW", "210,000 – 255,000", "~3,500", "4-5 years"],
            ["5 kW", "275,000 – 350,000", "~4,500", "3-4 years"],
            ["10 kW", "500,000 – 650,000", "~9,000", "3-4 years"]
          ]
        }
      },
      {
        heading: "Factors Affecting Solar Panel Prices",
        paragraphs: [
          "Several key factors influence the final cost of a solar installation in Bangladesh:"
        ],
        list: [
          "Panel technology: Monocrystalline panels cost 10-15% more than polycrystalline but deliver 3-5% higher efficiency",
          "Inverter type: String inverters are cheapest, while micro-inverters add 15-20% but improve per-panel optimization",
          "Mounting system: Rooftop installations are simpler and cheaper; ground-mount systems require additional structural work",
          "Battery storage: Adding lithium-ion batteries for backup can increase costs by BDT 80,000-200,000 depending on capacity",
          "Installation complexity: Multi-story buildings, shading issues, or long cable runs add to labor costs"
        ]
      },
      {
        heading: "Government Incentives and Tax Benefits",
        paragraphs: [
          "The Bangladesh government offers several incentives that effectively reduce the net cost of going solar. Import duty on solar equipment has been reduced to just 1%, and VAT exemptions apply to most solar components. Additionally, the IDCOL Solar Home System program provides subsidized financing for rural installations.",
          "Under the net metering policy, excess electricity generated by your solar system is fed back to the grid, earning credits on your electricity bill. This can effectively eliminate your electricity costs entirely for properly sized systems."
        ]
      },
      {
        heading: "Making the Investment Decision",
        paragraphs: [
          "With current prices and incentives, solar energy in Bangladesh offers one of the best returns on investment available to homeowners and businesses. A typical 5kW system pays for itself in 3-4 years and continues generating free electricity for 20+ more years. The combination of falling panel prices, government support, and rising electricity tariffs makes 2025 an ideal time to invest in solar."
        ],
        callout: {
          title: "Ready to Get Your Custom Quote?",
          text: "Every installation is unique. Contact our team for a free site survey and personalized quote based on your roof area, electricity consumption, and budget. We serve Dhaka, Chittagong, Sylhet, Rajshahi, and all major cities across Bangladesh."
        }
      }
    ]
  },
  "2": {
    sections: [
      {
        heading: "Understanding the 3000 MW Solar Program",
        paragraphs: [
          "The Bangladesh government has launched an ambitious 3,000 MW rooftop solar program as part of its Renewable Energy Policy and Vision 2041 targets. This initiative aims to transform rooftops across the country into clean energy generators, reducing dependence on imported fossil fuels while cutting carbon emissions.",
          "The program is coordinated by SREDA (Sustainable and Renewable Energy Development Authority) in partnership with local distribution companies (DISCOs) and financial institutions."
        ]
      },
      {
        heading: "Who Is Eligible?",
        paragraphs: [
          "The program is open to a wide range of applicants across Bangladesh:"
        ],
        list: [
          "Residential homeowners with suitable rooftop space (minimum 100 sq ft for 1kW)",
          "Commercial buildings including offices, shopping complexes, and restaurants",
          "Industrial facilities such as garment factories, food processing plants, and warehouses",
          "Government and institutional buildings including schools, hospitals, and mosques",
          "Agricultural operations for solar-powered irrigation and cold storage"
        ]
      },
      {
        heading: "Step-by-Step Application Process",
        paragraphs: [
          "Applying for the 3,000 MW program involves several steps, but the process has been streamlined significantly in 2025:"
        ],
        list: [
          "Step 1: Contact your local DISCO (DPDC, DESCO, BPDB, etc.) and obtain the net metering application form",
          "Step 2: Submit your application with property ownership documents, electricity bill copies, and proposed system design",
          "Step 3: DISCO conducts a technical feasibility assessment of your premises (usually within 15 working days)",
          "Step 4: Receive approval and install your system through an SREDA-certified installer",
          "Step 5: DISCO inspects the installation and installs a bi-directional meter",
          "Step 6: Sign the net metering agreement and start generating clean energy"
        ]
      },
      {
        heading: "Financial Benefits Under the Program",
        paragraphs: [
          "Participants in the 3,000 MW program enjoy multiple financial advantages. Net metering allows you to sell excess power back to the grid at retail rates, effectively using the grid as a virtual battery. Many banks now offer dedicated solar loans at 8-9% interest rates with up to 5-year repayment terms.",
          "The combination of reduced electricity bills, net metering income, and tax benefits means most installations achieve full payback within 3-4 years, with the system continuing to generate returns for 20+ more years."
        ]
      },
      {
        heading: "Common Challenges and How to Overcome Them",
        paragraphs: [
          "While the program is well-designed, applicants sometimes face delays in DISCO approvals or meter installation. To minimize issues, work with an experienced SREDA-certified installer who can handle all paperwork, ensure your electrical system meets safety standards before applying, and maintain communication with your local DISCO office throughout the process."
        ],
        callout: {
          title: "Need Help Applying?",
          text: "Our team has helped over 500 customers navigate the 3,000 MW program application process. We handle all paperwork, DISCO coordination, and installation. Contact us for a free consultation."
        }
      }
    ]
  },
  "3": {
    sections: [
      {
        heading: "Why a 5kW System Is the Sweet Spot",
        paragraphs: [
          "A 5kW solar system has emerged as the most popular choice for medium to large homes in Bangladesh. It generates approximately 20-25 kWh of electricity per day — enough to power air conditioning, refrigerators, lighting, fans, and other household appliances while still having surplus energy to sell back to the grid.",
          "At a price range of BDT 275,000-350,000, the 5kW system offers the best balance of upfront cost, energy production, and return on investment."
        ]
      },
      {
        heading: "Monthly Savings Calculation",
        paragraphs: [
          "Let's break down the real savings you can expect from a 5kW system in Bangladesh:"
        ],
        table: {
          headers: ["Parameter", "Value"],
          rows: [
            ["Daily generation", "20-25 kWh (avg 22 kWh)"],
            ["Monthly generation", "~660 kWh"],
            ["Average tariff rate", "BDT 6.80/kWh"],
            ["Monthly electricity saved", "BDT 4,488"],
            ["Net metering credit (excess)", "BDT 500-1,500/month"],
            ["Total monthly benefit", "BDT 4,500-6,000"],
            ["Annual savings", "BDT 54,000-72,000"]
          ]
        }
      },
      {
        heading: "25-Year Financial Projection",
        paragraphs: [
          "Solar panels are designed to last 25-30 years with minimal degradation. Here's what your long-term returns look like assuming 5% annual electricity price increases and 0.5% annual panel degradation:",
          "Year 1-4: Investment recovery phase. Your system pays for itself by the end of year 3-4. Year 5-10: Pure savings phase — you earn BDT 300,000-400,000 in avoided electricity costs. Year 11-25: Long-term returns accumulate to BDT 1,500,000-2,000,000 in total lifetime savings. Even accounting for inverter replacement (around year 12-15 at BDT 40,000-60,000), the total ROI exceeds 500%."
        ]
      },
      {
        heading: "Factors That Improve Your ROI",
        paragraphs: [
          "Several factors can significantly improve your return on investment:"
        ],
        list: [
          "South-facing roof with minimal shading maximizes energy production",
          "Regular panel cleaning (monthly) maintains peak efficiency — especially important during dusty dry seasons",
          "Time-of-use optimization: Run heavy appliances during peak solar hours (10 AM - 3 PM)",
          "Net metering enrollment ensures you get credit for every kWh of excess generation",
          "Proper system sizing: Oversizing by 10-15% compensates for monsoon season reduction"
        ]
      },
      {
        heading: "Is a 5kW System Right for You?",
        paragraphs: [
          "A 5kW system is ideal if your monthly electricity bill exceeds BDT 3,000, you have at least 300-350 sq ft of unshaded roof space, and your home uses air conditioning or other high-consumption appliances. For smaller homes with bills under BDT 2,000, a 2-3kW system may be more appropriate."
        ],
        callout: {
          title: "Calculate Your Exact Savings",
          text: "Use our AI-powered Solar Calculator tool to get a personalized ROI analysis based on your actual electricity consumption, roof dimensions, and location. Try it now on our AI Tools page."
        }
      }
    ]
  },
  "4": {
    sections: [
      {
        heading: "How We Ranked the Top Solar Companies",
        paragraphs: [
          "Our ranking methodology considers installation quality, customer reviews, pricing transparency, after-sales service, warranty terms, and years of experience in the Bangladesh market. We surveyed over 200 customers and evaluated 25+ companies to compile this definitive list for 2025."
        ]
      },
      {
        heading: "What to Look for in a Solar Installer",
        paragraphs: [
          "Before choosing a solar company, evaluate these critical factors:"
        ],
        list: [
          "SREDA certification: Ensures the company meets government quality standards for solar installations",
          "Track record: Look for companies with 100+ completed installations and verifiable references",
          "Warranty coverage: Minimum 10-year warranty on workmanship, 25-year on panels, 5-10 year on inverters",
          "Panel brands: Tier-1 manufacturers like Trina Solar, JA Solar, Longi, and REC offer the best long-term reliability",
          "After-sales service: On-site response time should be within 24-48 hours for warranty claims",
          "Net metering support: The company should handle all DISCO paperwork and meter installation coordination",
          "Transparent pricing: Beware of companies that don't provide itemized quotes or push for immediate deposits"
        ]
      },
      {
        heading: "Key Market Trends in 2025",
        paragraphs: [
          "The Bangladesh solar installation market has matured significantly. Companies are now offering comprehensive packages that include panels, inverters, mounting, wiring, installation, net metering setup, and annual maintenance — all in one price. Financing partnerships with banks like BRAC Bank, City Bank, and Eastern Bank have made EMI options widely available.",
          "We're also seeing increased adoption of monitoring apps that let customers track their system's performance in real-time via smartphone, adding transparency and peace of mind to the solar ownership experience."
        ]
      },
      {
        heading: "Red Flags to Watch Out For",
        paragraphs: [
          "Unfortunately, the booming solar market has attracted some unreliable operators. Watch out for these warning signs:"
        ],
        list: [
          "Prices significantly below market average — likely using inferior components or cutting corners on installation",
          "No SREDA certification or unwillingness to show credentials",
          "Pressure to sign contracts immediately without allowing time for comparison",
          "Vague or verbal-only warranty promises instead of written documentation",
          "No physical office or showroom — legitimate companies maintain visible business premises"
        ]
      },
      {
        heading: "Making Your Final Decision",
        paragraphs: [
          "We recommend getting quotes from at least 3 companies, visiting their completed installations if possible, and checking online reviews on Facebook groups and Google. The right installer will be transparent, patient with your questions, and willing to provide references from previous customers in your area."
        ],
        callout: {
          title: "Want Our Recommendation?",
          text: "Tell us your location, system size, and budget, and we'll match you with the best-rated installer in your area. Our consultation is completely free and unbiased."
        }
      }
    ]
  },
  "5": {
    sections: [
      {
        heading: "What Is Net Metering?",
        paragraphs: [
          "Net metering is a billing mechanism that allows solar panel owners to feed excess electricity back into the national grid and receive credits on their electricity bill. In Bangladesh, this policy was formalized through the Net Metering Guidelines 2018 and has been expanded under the 3,000 MW rooftop solar program.",
          "When your solar panels generate more electricity than you consume (typically during midday), the excess flows into the grid through a bi-directional meter. Your DISCO credits this excess against your nighttime or cloudy-day consumption, effectively using the grid as a free battery."
        ]
      },
      {
        heading: "How Net Metering Works in Bangladesh",
        paragraphs: [
          "The net metering process in Bangladesh follows a monthly billing cycle:"
        ],
        list: [
          "Your bi-directional meter tracks both electricity consumed from the grid (import) and electricity sent to the grid (export)",
          "At the end of each billing cycle, your DISCO calculates the net difference",
          "If you consumed more than you generated, you pay only for the net difference",
          "If you generated more than you consumed, the excess credit carries forward to the next month",
          "Credits can accumulate for up to 12 months before settlement",
          "Settlement rates are based on the applicable retail tariff for your consumer category"
        ]
      },
      {
        heading: "Eligible Distribution Companies (DISCOs)",
        paragraphs: [
          "Net metering is available through all major distribution companies in Bangladesh:"
        ],
        table: {
          headers: ["DISCO", "Coverage Area", "Application Office"],
          rows: [
            ["DPDC", "Dhaka South, Old Dhaka", "Dhaka Power HQ"],
            ["DESCO", "Dhaka North, Uttara, Tongi", "DESCO Mirpur Office"],
            ["BPDB", "Chittagong, Sylhet, Other cities", "Regional BPDB offices"],
            ["WZPDCL", "Western Bangladesh", "Rajshahi Division Office"],
            ["NESCO", "Northern Bangladesh", "Rangpur Division Office"],
            ["BREB", "Rural areas nationwide", "Local PBS offices"]
          ]
        }
      },
      {
        heading: "Maximizing Your Net Metering Benefits",
        paragraphs: [
          "To get the most from net metering, size your system to generate 100-120% of your annual consumption. This ensures maximum self-consumption during the day while generating enough excess to offset nighttime usage. Installing a smart energy management system can further optimize by scheduling high-consumption appliances (water heaters, washing machines, EV charging) during peak solar hours.",
          "Keep in mind that net metering credits are settled at the end of each 12-month cycle, so it's beneficial to have your system slightly oversized to build up credits during the sunny winter months that carry through the monsoon season."
        ]
      },
      {
        heading: "Common Questions About Net Metering",
        paragraphs: [
          "Many homeowners wonder about the safety and reliability of grid-connected solar systems. Modern inverters include anti-islanding protection, meaning your system automatically shuts down during grid outages to protect utility workers. If you want power during outages, you'll need a hybrid inverter with battery storage — an increasingly popular add-on in Bangladesh."
        ],
        callout: {
          title: "Start Your Net Metering Journey",
          text: "Our team handles the entire net metering application process, from DISCO paperwork to meter installation. We've successfully connected over 300 systems to the grid across Bangladesh."
        }
      }
    ]
  },
  "6": {
    sections: [
      {
        heading: "The Challenge: Skyrocketing Electricity Costs",
        paragraphs: [
          "Located in the Chittagong Export Processing Zone, this mid-size textile factory was spending over BDT 25 lakh per month on electricity. With 12-hour production shifts, heavy machinery including looms, dyeing units, and climate control systems, electricity was the single largest operational expense — eating into profit margins already under pressure from global competition.",
          "The factory management explored several options including diesel generators and energy efficiency upgrades before deciding that solar offered the best long-term solution."
        ]
      },
      {
        heading: "System Design and Installation",
        paragraphs: [
          "Our engineering team designed a 200kW rooftop solar system tailored to the factory's specific requirements:"
        ],
        table: {
          headers: ["Component", "Specification", "Quantity"],
          rows: [
            ["Solar Panels", "550W Mono PERC (Tier-1)", "364 panels"],
            ["Inverters", "50kW String Inverters", "4 units"],
            ["Mounting", "Industrial flush-mount rails", "Full roof coverage"],
            ["Monitoring", "Cloud-based SCADA system", "1 system"],
            ["Net Metering", "Bi-directional CT meters", "1 set"]
          ]
        }
      },
      {
        heading: "Installation Challenges and Solutions",
        paragraphs: [
          "The installation presented several unique challenges that our team successfully addressed:"
        ],
        list: [
          "Structural assessment: The factory roof required reinforcement in two sections to support panel weight — completed without disrupting production",
          "Production continuity: Installation was phased over 3 weekends to minimize downtime, with electrical connections done during scheduled maintenance windows",
          "Monsoon planning: The system was designed with enhanced drainage channels and wind-resistant mounting to handle Chittagong's severe weather",
          "Grid compatibility: Coordination with BPDB Chittagong for 200kW net metering approval required specialized transformer and protection equipment"
        ]
      },
      {
        heading: "Results: 18 Months Post-Installation",
        paragraphs: [
          "The results exceeded initial projections:"
        ],
        table: {
          headers: ["Metric", "Before Solar", "After Solar", "Improvement"],
          rows: [
            ["Monthly electricity bill", "BDT 25,00,000", "BDT 8,75,000", "65% reduction"],
            ["Monthly savings", "—", "BDT 16,25,000", "—"],
            ["Annual savings", "—", "BDT 1,95,00,000", "—"],
            ["Carbon offset", "—", "240 tons CO₂/year", "—"],
            ["System payback", "—", "2.8 years", "Expected 3.5 years"]
          ]
        }
      },
      {
        heading: "Lessons for Other Manufacturers",
        paragraphs: [
          "This case study demonstrates that commercial solar installations in Bangladesh offer exceptional returns, particularly for energy-intensive manufacturing operations. The key success factors were proper system sizing based on actual load profiles, choosing a Tier-1 panel brand for long-term reliability, and working with an installer experienced in industrial-scale projects."
        ],
        callout: {
          title: "Is Your Factory Ready for Solar?",
          text: "We specialize in 50kW-1MW commercial installations across Bangladesh. Contact us for a free energy audit and custom proposal for your manufacturing facility."
        }
      }
    ]
  },
  "7": {
    sections: [
      {
        heading: "Why Maintenance Matters in Bangladesh",
        paragraphs: [
          "Bangladesh's tropical climate presents unique challenges for solar panel maintenance. High humidity, monsoon rains, dust accumulation during dry seasons, and occasional cyclonic conditions can all reduce panel efficiency by 15-25% if not properly addressed. Regular maintenance ensures your system operates at peak performance and extends its lifespan well beyond the standard 25-year warranty."
        ]
      },
      {
        heading: "Monthly Cleaning Schedule",
        paragraphs: [
          "A consistent cleaning routine is the single most impactful maintenance activity for solar panels in Bangladesh:"
        ],
        list: [
          "Dry season (October-March): Clean panels every 2 weeks. Dust, pollen, and bird droppings accumulate faster without rain to wash them away",
          "Pre-monsoon (April-May): Deep clean before monsoon season. Remove any debris that could trap moisture",
          "Monsoon season (June-September): Monthly inspection is sufficient — rain provides natural cleaning, but check for algae or moss growth on frames",
          "Post-monsoon (October): Thorough inspection and cleaning after monsoon to address any weather damage"
        ]
      },
      {
        heading: "Safe Cleaning Techniques",
        paragraphs: [
          "Proper cleaning technique is essential to avoid damaging your panels:"
        ],
        list: [
          "Use soft water (filtered or rainwater) to avoid mineral deposits — hard tap water leaves white residue that reduces efficiency",
          "Clean early morning or late evening when panels are cool — cold water on hot panels can cause thermal shock and micro-cracks",
          "Use a soft sponge or microfiber cloth — never abrasive materials, steel wool, or high-pressure washers",
          "Apply gentle soap solution (dish soap) for stubborn stains — avoid harsh chemicals or detergents",
          "Rinse thoroughly to remove all soap residue",
          "Never walk on panels — use extension poles or hire professional cleaners for hard-to-reach installations"
        ]
      },
      {
        heading: "Electrical System Checks",
        paragraphs: [
          "Beyond panel cleaning, regular electrical checks prevent costly failures:",
          "Inspect all cable connections quarterly for signs of corrosion, looseness, or insect/rodent damage. Check junction boxes for moisture ingress — a common issue in Bangladesh's humid climate. Monitor inverter performance weekly through its display or monitoring app; any significant drop in efficiency could indicate a wiring issue. Test earth connections annually, especially before monsoon season, to ensure lightning protection is intact."
        ]
      },
      {
        heading: "When to Call a Professional",
        paragraphs: [
          "While basic cleaning can be DIY, certain maintenance tasks require professional attention: hotspot detection using thermal imaging, inverter servicing, structural mounting checks after severe weather events, and any electrical troubleshooting. Most reputable installers offer annual maintenance contracts (AMC) at BDT 5,000-15,000/year depending on system size."
        ],
        callout: {
          title: "Annual Maintenance Contract",
          text: "Our AMC packages include quarterly cleaning, bi-annual electrical inspection, thermal imaging, and 24/7 monitoring. Starting at just BDT 5,000/year for residential systems."
        }
      }
    ]
  },
  "8": {
    sections: [
      {
        heading: "Understanding Panel Technologies",
        paragraphs: [
          "The two dominant solar panel technologies available in Bangladesh are monocrystalline and polycrystalline (also called multicrystalline). Both use silicon-based photovoltaic cells but differ significantly in manufacturing process, efficiency, appearance, cost, and performance characteristics. Understanding these differences is crucial for making the right choice for your specific installation."
        ]
      },
      {
        heading: "Efficiency Comparison",
        paragraphs: [
          "Efficiency — how much sunlight a panel converts to electricity — is the most critical performance metric:"
        ],
        table: {
          headers: ["Feature", "Monocrystalline", "Polycrystalline"],
          rows: [
            ["Efficiency range", "20-22%", "15-17%"],
            ["Temperature coefficient", "-0.35%/°C", "-0.45%/°C"],
            ["Low-light performance", "Better", "Moderate"],
            ["Space required (5kW)", "~280 sq ft", "~350 sq ft"],
            ["Appearance", "Uniform black", "Blue, speckled"],
            ["Lifespan", "30+ years", "25-30 years"],
            ["Price (per watt)", "BDT 55-65", "BDT 40-50"]
          ]
        }
      },
      {
        heading: "Performance in Bangladesh's Climate",
        paragraphs: [
          "Bangladesh's tropical climate, with average temperatures of 28-35°C and high humidity, significantly impacts panel performance. This is where monocrystalline panels show a clear advantage.",
          "The temperature coefficient difference is critical: monocrystalline panels lose about 0.35% efficiency per degree above 25°C, while polycrystalline panels lose 0.45%. On a typical 40°C summer day in Dhaka, this means monocrystalline panels retain 94.75% efficiency while polycrystalline retain 93.25% — a meaningful difference over 25 years of operation.",
          "Monocrystalline panels also perform significantly better during monsoon season when diffused light conditions prevail. Their superior low-light response means they generate 10-15% more electricity on cloudy days compared to polycrystalline equivalents."
        ]
      },
      {
        heading: "Cost-Benefit Analysis for Bangladesh",
        paragraphs: [
          "While monocrystalline panels cost 20-30% more upfront, the higher efficiency means you need fewer panels to achieve the same output — reducing mounting hardware, wiring, and installation labor costs. For space-constrained rooftops common in Dhaka and other cities, monocrystalline panels are often the only practical choice.",
          "Over a 25-year period, monocrystalline panels generate approximately 15-20% more electricity per panel, making the total cost per kWh generated actually lower than polycrystalline despite the higher upfront price."
        ]
      },
      {
        heading: "Our Recommendation",
        paragraphs: [
          "For most installations in Bangladesh, we recommend monocrystalline panels due to their superior heat tolerance, better monsoon performance, and higher energy density per square foot. Polycrystalline panels remain a valid budget option for large rooftops (factories, warehouses) where space is not a constraint and upfront cost is the primary concern."
        ],
        callout: {
          title: "Compare Panels for Your Roof",
          text: "Our AI Solar Analyzer can model both panel types on your specific roof, accounting for local weather patterns, shading, and orientation. Get a customized comparison with our AI Tools."
        }
      }
    ]
  },
  "9": {
    sections: [
      {
        heading: "Seasonal Solar Performance in Bangladesh",
        paragraphs: [
          "Bangladesh experiences distinct seasons that significantly impact solar energy production. Understanding these patterns helps you choose the optimal installation timing to maximize your first-year returns and avoid weather-related delays.",
          "Peak solar irradiation occurs from October through March (dry season), with daily sunshine averaging 5-6 hours. The monsoon season (June-September) sees reduced output of 3-4 hours equivalent, while the pre-monsoon period (April-May) offers excellent production despite higher temperatures."
        ]
      },
      {
        heading: "Why Spring (February-April) Is Ideal",
        paragraphs: [
          "Installing your solar system between February and April offers several compelling advantages:"
        ],
        list: [
          "Immediate high output: Your system begins generating maximum electricity right away during peak sunshine months",
          "Dry weather for installation: No rain delays mean faster project completion (typically 1-2 days for residential)",
          "Beat the summer rush: Installer availability is better in early spring before the summer demand surge",
          "Pre-monsoon preparation: Your system is tested and optimized before the challenging monsoon months",
          "Maximum first-year ROI: Starting in spring means capturing the best 4-5 months of production before monsoon, versus starting in monsoon and losing 3-4 months of peak output"
        ]
      },
      {
        heading: "Monthly Solar Production Estimates (5kW System)",
        paragraphs: [
          "Here's what a typical 5kW system produces throughout the year in Dhaka:"
        ],
        table: {
          headers: ["Month", "Daily Production (kWh)", "Monthly Total (kWh)"],
          rows: [
            ["January", "21", "651"],
            ["February", "22", "616"],
            ["March", "24", "744"],
            ["April", "23", "690"],
            ["May", "20", "620"],
            ["June", "16", "480"],
            ["July", "14", "434"],
            ["August", "15", "465"],
            ["September", "17", "510"],
            ["October", "20", "620"],
            ["November", "21", "630"],
            ["December", "20", "620"]
          ]
        }
      },
      {
        heading: "Avoiding Installation Pitfalls by Season",
        paragraphs: [
          "Each season presents unique considerations. During monsoon (June-September), roof work is risky and unreliable — avoid scheduling installations during this period unless absolutely necessary. Summer heat (April-June) makes rooftop work challenging for installers, potentially rushing the job. Winter (December-January) is good for installation but morning fog in northern regions can delay start times. The sweet spot of February-March offers comfortable working temperatures, dry conditions, and motivated installation crews."
        ]
      },
      {
        heading: "Planning Your Installation Timeline",
        paragraphs: [
          "For the best experience, start planning 4-6 weeks before your desired installation date. This allows time for site survey, system design, equipment procurement, DISCO application (if net metering), and scheduling. If you're planning a spring installation, begin the process in January to ensure everything is ready."
        ],
        callout: {
          title: "Book Your Spring Installation Now",
          text: "Our spring installation slots fill up quickly. Contact us today to reserve your installation date and lock in current pricing before the seasonal rush."
        }
      }
    ]
  },
  "10": {
    sections: [
      {
        heading: "Solar Financing Landscape in Bangladesh",
        paragraphs: [
          "One of the biggest barriers to solar adoption in Bangladesh has been the upfront cost. However, 2025 has seen a dramatic expansion in financing options, making solar accessible to virtually any homeowner or business. From bank loans to EMI plans and green financing programs, there are now multiple paths to going solar with zero or minimal upfront payment."
        ]
      },
      {
        heading: "Bank Solar Loan Programs",
        paragraphs: [
          "Several major banks in Bangladesh now offer dedicated solar loan products:"
        ],
        table: {
          headers: ["Bank", "Interest Rate", "Max Tenure", "Max Amount", "Processing Fee"],
          rows: [
            ["BRAC Bank", "8%", "5 years", "BDT 20 lakh", "1%"],
            ["City Bank", "8.5%", "5 years", "BDT 15 lakh", "1.5%"],
            ["Eastern Bank", "9%", "4 years", "BDT 10 lakh", "1%"],
            ["IDLC Finance", "9%", "5 years", "BDT 25 lakh", "1%"],
            ["Mutual Trust Bank", "8.5%", "4 years", "BDT 12 lakh", "1%"]
          ]
        }
      },
      {
        heading: "EMI Options Explained",
        paragraphs: [
          "For a typical 5kW system costing BDT 300,000 with an 8% interest rate over 5 years, your monthly EMI would be approximately BDT 6,080. Since your solar system saves BDT 4,500-6,000 per month on electricity, the net monthly cost is nearly zero — you're essentially swapping your electricity bill for a loan payment, but the loan ends while the solar savings continue for 20+ more years.",
          "Some installers also offer in-house EMI plans with 0% interest for 12-24 months, though these typically have higher base prices built in. Compare the total cost carefully before choosing between bank financing and installer EMI plans."
        ]
      },
      {
        heading: "Government and International Funding",
        paragraphs: [
          "Additional financing sources include:"
        ],
        list: [
          "IDCOL Green Finance: Subsidized loans for rural solar installations with interest rates as low as 6%",
          "ADB LEAP 2 Program: $515 million in renewable energy financing channeled through local banks",
          "World Bank RE Financing: Available through participating banks with concessional terms",
          "Green Climate Fund: Supporting large-scale commercial solar projects through local financial intermediaries",
          "Microfinance options: Grameen Shakti and BRAC offer small solar system financing for rural households"
        ]
      },
      {
        heading: "Choosing the Right Financing Option",
        paragraphs: [
          "The best financing option depends on your situation: bank loans offer the lowest interest rates but require credit history and documentation. In-house EMI plans are simpler to arrange but may cost more overall. Government programs offer the best rates but have eligibility criteria and slower processing. We recommend getting quotes for all available options and comparing the total cost of ownership over the loan period."
        ],
        callout: {
          title: "Zero Down Payment Solar",
          text: "Ask about our partnership with leading banks for zero down payment solar installations. Subject to credit approval, you can go solar today with no upfront cost and start saving immediately."
        }
      }
    ]
  },
  "11": {
    sections: [
      {
        heading: "Solar Potential Across Dhaka",
        paragraphs: [
          "Dhaka, with its dense urban landscape and approximately 20 million residents, has enormous untapped solar potential. Rooftop solar is particularly well-suited to the city's building stock, where flat concrete roofs are the norm. Despite the urban heat island effect and occasional air quality issues, Dhaka receives excellent solar irradiation averaging 4.5-5.5 peak sun hours daily, making it one of the best cities for solar in South Asia."
        ]
      },
      {
        heading: "Area-Specific Coverage",
        paragraphs: [
          "Solar installation characteristics vary by neighborhood due to building types, grid infrastructure, and local regulations:"
        ],
        table: {
          headers: ["Area", "Typical System", "DISCO", "Key Consideration"],
          rows: [
            ["Gulshan", "5-10 kW", "DESCO", "High-rise buildings, shading analysis critical"],
            ["Dhanmondi", "3-5 kW", "DPDC", "Older buildings may need roof reinforcement"],
            ["Uttara", "5-10 kW", "DESCO", "Newer buildings, excellent roof access"],
            ["Mirpur", "3-5 kW", "DESCO", "Dense area, panel orientation important"],
            ["Bashundhara", "5-10 kW", "DESCO", "Modern buildings, ideal for large systems"],
            ["Mohammadpur", "3-5 kW", "DPDC", "Mixed building types, varied roof quality"],
            ["Banani", "5-10 kW", "DESCO", "Commercial buildings, high electricity costs"],
            ["Motijheel", "10-50 kW", "DPDC", "Commercial district, industrial-scale systems"]
          ]
        }
      },
      {
        heading: "Dhaka-Specific Regulations",
        paragraphs: [
          "Dhaka has specific considerations for solar installations that differ from other parts of Bangladesh. Both DPDC and DESCO have streamlined their net metering application processes, with approval typically taking 15-30 working days. RAJUK (Dhaka development authority) does not require additional building permits for rooftop solar installations that don't alter the building structure.",
          "However, installations on heritage buildings in Old Dhaka require special approval. Multi-unit residential buildings need consent from the building management committee, and systems exceeding 50kW may require transformer upgrades at the owner's expense."
        ]
      },
      {
        heading: "Unique Challenges in Dhaka",
        paragraphs: [
          "Urban solar installations in Dhaka face challenges not found in rural areas:"
        ],
        list: [
          "Shading from neighboring buildings — requires careful site survey and sometimes micro-inverters for partial shading optimization",
          "Limited roof access — installations on 8-10 story buildings need crane access, adding to installation costs",
          "Air pollution — dust and particulate matter from traffic requires more frequent panel cleaning (every 1-2 weeks)",
          "Building owner coordination — tenant-occupied buildings need landlord and management committee approval",
          "Cable routing in multi-story buildings can be complex and require additional electrical work"
        ]
      },
      {
        heading: "Dhaka Solar Installation Services",
        paragraphs: [
          "Our Dhaka team covers all areas within DPDC and DESCO jurisdictions. We maintain relationships with both DISCOs for expedited net metering processing and have experience with all building types from single-family homes to commercial high-rises."
        ],
        callout: {
          title: "Free Site Survey in Dhaka",
          text: "We offer free rooftop assessment and solar design for all Dhaka addresses. Our team will visit your location, measure your roof, analyze shading, and provide a custom proposal within 48 hours."
        }
      }
    ]
  },
  "12": {
    sections: [
      {
        heading: "Why Industries Are Going Solar",
        paragraphs: [
          "Bangladesh's industrial sector consumes over 60% of the country's electricity, with factories paying commercial rates that are 30-50% higher than residential tariffs. For energy-intensive industries — garments, textiles, steel, ceramics, food processing — electricity costs directly impact competitiveness in global markets. Solar installations of 100kW to 1MW offer transformative savings while enhancing environmental credentials increasingly demanded by international buyers."
        ]
      },
      {
        heading: "Industry-Specific Solutions",
        paragraphs: [
          "Different industries have different energy profiles that affect solar system design:"
        ],
        table: {
          headers: ["Industry", "Typical System", "Annual Savings", "Payback"],
          rows: [
            ["Garment Factory", "200-500 kW", "BDT 1.5-4 Cr", "2.5-3.5 years"],
            ["Textile Mill", "300-1 MW", "BDT 2-8 Cr", "2-3 years"],
            ["Food Processing", "100-300 kW", "BDT 80L-2.5 Cr", "3-4 years"],
            ["Pharmaceuticals", "150-400 kW", "BDT 1-3 Cr", "2.5-3.5 years"],
            ["Cold Storage", "50-200 kW", "BDT 40L-1.5 Cr", "3-4 years"],
            ["IT/Office Complex", "100-300 kW", "BDT 70L-2 Cr", "3-4 years"]
          ]
        }
      },
      {
        heading: "Financing for Industrial Solar",
        paragraphs: [
          "Large-scale industrial installations have access to specialized financing mechanisms:"
        ],
        list: [
          "Power Purchase Agreements (PPA): A third-party investor installs and owns the system — you simply buy the power at a fixed rate lower than grid tariff, with zero upfront cost",
          "ESCO Model: Energy Service Companies finance, install, and maintain the system in exchange for a share of energy savings",
          "Commercial bank loans: Dedicated green energy credit lines at 7-9% interest with up to 7-year tenure",
          "IFC/ADB project financing: Available for installations above 500kW through participating banks",
          "Leasing: Some companies offer solar system leasing where monthly payments are set below current electricity costs"
        ]
      },
      {
        heading: "Compliance and Green Certification",
        paragraphs: [
          "International buyers increasingly require proof of sustainable practices. Solar installations help factories achieve LEED certification, comply with EU Carbon Border Adjustment Mechanism (CBAM) requirements, and meet buyer sustainability mandates from brands like H&M, Zara, and Nike. Several Bangladeshi garment exporters have reported winning new contracts specifically because of their solar installations and reduced carbon footprint."
        ]
      },
      {
        heading: "Implementation Timeline",
        paragraphs: [
          "A typical industrial solar project takes 8-16 weeks from initial survey to commissioning: 2-3 weeks for site assessment and design, 2-3 weeks for procurement, 3-6 weeks for installation, and 1-4 weeks for grid connection and commissioning. We plan installations to minimize production disruption, typically working during weekends and scheduled maintenance windows."
        ],
        callout: {
          title: "Industrial Solar Consultation",
          text: "Our industrial solar team has completed 50+ factory installations across Bangladesh. We offer free energy audits and ROI analysis for manufacturing facilities. Contact us to schedule a site visit."
        }
      }
    ]
  },
  "13": {
    sections: [
      {
        heading: "How Heat Affects Solar Panels",
        paragraphs: [
          "A common misconception is that solar panels produce more electricity in hotter weather because there's more sunshine. In reality, while more sunshine does mean more energy, excessive heat actually reduces panel efficiency. Every solar panel has a temperature coefficient — the rate at which efficiency drops for each degree above the standard test condition of 25°C.",
          "In Bangladesh, where summer temperatures regularly exceed 35-40°C and rooftop temperatures can reach 50-60°C, understanding and mitigating heat effects is critical for system performance."
        ]
      },
      {
        heading: "Temperature Impact by Panel Type",
        paragraphs: [
          "Different panel technologies respond differently to heat:"
        ],
        table: {
          headers: ["Panel Type", "Temp Coefficient", "Output at 45°C", "Output at 55°C"],
          rows: [
            ["Standard Mono PERC", "-0.35%/°C", "93%", "89.5%"],
            ["HJT (Heterojunction)", "-0.26%/°C", "94.8%", "92.2%"],
            ["N-type TOPCon", "-0.30%/°C", "94%", "91%"],
            ["Polycrystalline", "-0.45%/°C", "91%", "86.5%"],
            ["Thin Film (CdTe)", "-0.25%/°C", "95%", "92.5%"]
          ]
        }
      },
      {
        heading: "Heat Mitigation Strategies",
        paragraphs: [
          "Several practical strategies can reduce heat-related efficiency losses on Bangladesh rooftops:"
        ],
        list: [
          "Elevated mounting: Leave 6-8 inches of gap between panels and roof surface for air circulation — this alone can reduce panel temperature by 10-15°C",
          "Light-colored roofing: White or reflective roofing beneath panels reduces ambient heat absorption",
          "Panel spacing: Adequate gaps between rows allow wind to cool panel undersides",
          "Water cooling: Some industrial installations use automated sprinkler systems during peak heat — effective but adds maintenance complexity",
          "Micro-inverter optimization: Per-panel optimization ensures hot panels don't drag down the performance of cooler ones in the same string",
          "Strategic orientation: Slight west-facing tilt can shift peak production to afternoon hours, avoiding the hottest midday period"
        ]
      },
      {
        heading: "Seasonal Performance Patterns",
        paragraphs: [
          "In Bangladesh, the hottest months (April-June) coincide with longer daylight hours, creating a trade-off between more sunshine and higher temperatures. The net effect is that March and October typically produce the highest monthly output — benefiting from good sunshine without extreme heat. Smart system design accounts for this seasonal variation to optimize annual production."
        ]
      },
      {
        heading: "Choosing Heat-Resistant Panels for Bangladesh",
        paragraphs: [
          "For installations in Bangladesh, we recommend panels with temperature coefficients of -0.35%/°C or better. HJT and N-type TOPCon panels offer the best heat tolerance but come at a premium. For budget-conscious installations, standard Mono PERC panels with proper elevated mounting provide excellent value. Avoid polycrystalline panels for rooftop installations where heat build-up is significant."
        ],
        callout: {
          title: "Get a Heat-Optimized Design",
          text: "Our engineers use thermal modeling software to design installations that minimize heat losses on your specific roof. Contact us for a free thermal assessment."
        }
      }
    ]
  },
  "14": {
    sections: [
      {
        heading: "Why Hospitals Need Solar + Battery",
        paragraphs: [
          "Healthcare facilities have unique power requirements that make them ideal candidates for solar energy systems. Unlike homes or offices that can tolerate brief power interruptions, hospitals depend on uninterrupted power for life-support equipment, operating theaters, vaccine refrigeration, diagnostic imaging, and patient monitoring systems. In Bangladesh, where grid outages and load shedding remain common, solar with battery backup provides a reliable, cost-effective alternative to diesel generators."
        ]
      },
      {
        heading: "Case Study: 100-Bed Hospital in Dhaka",
        paragraphs: [
          "A private 100-bed hospital in Dhaka's Mohammadpur area was spending BDT 8 lakh monthly on electricity and BDT 3 lakh on diesel for backup generators. The total energy cost of BDT 11 lakh per month was straining operational budgets and the diesel generator noise and emissions were causing complaints from patients and nearby residents."
        ],
        table: {
          headers: ["System Component", "Specification"],
          rows: [
            ["Solar Array", "80 kW rooftop (multi-level building)"],
            ["Battery Storage", "200 kWh Lithium Iron Phosphate (LiFePO4)"],
            ["Inverter System", "100 kVA hybrid (grid-tied + battery)"],
            ["Backup Duration", "4 hours at full hospital load"],
            ["UPS Integration", "Seamless transfer (<10ms) for critical loads"],
            ["Monitoring", "24/7 remote monitoring with alarm system"]
          ]
        }
      },
      {
        heading: "Critical Design Considerations",
        paragraphs: [
          "Hospital solar installations require special attention to several factors:"
        ],
        list: [
          "Seamless transfer: The hybrid inverter must switch from grid to battery in under 10 milliseconds — critical for life-support and monitoring equipment",
          "Load segregation: Critical loads (ICU, OT, labs) are on dedicated circuits with battery backup, while non-critical loads (lighting, admin) use grid-tied solar without battery",
          "Battery sizing: Minimum 4-hour backup for critical loads, accounting for worst-case scenarios including nighttime emergencies",
          "Redundancy: Dual inverter configuration ensures no single point of failure in the power system",
          "Fire safety: LiFePO4 batteries chosen over NMC chemistry for their superior thermal stability and fire resistance in hospital settings",
          "Maintenance access: System designed for maintenance without disrupting hospital operations"
        ]
      },
      {
        heading: "Results After 12 Months",
        paragraphs: [
          "The hospital reported dramatic improvements across all metrics. Monthly electricity costs dropped from BDT 8 lakh to BDT 3.2 lakh. Diesel consumption was reduced by 90%, saving BDT 2.7 lakh monthly and eliminating generator noise and emissions. Total monthly savings of BDT 7.5 lakh put the system on track for payback within 3 years.",
          "Perhaps most importantly, the battery system provided seamless backup during 47 grid outages over the year, maintaining uninterrupted power to critical equipment without a single generator start. This improved patient safety and staff confidence significantly."
        ]
      },
      {
        heading: "Scaling to Other Healthcare Facilities",
        paragraphs: [
          "The success of this installation has led to inquiries from hospitals, clinics, and diagnostic centers across Bangladesh. Solar + battery systems are particularly valuable for rural health centers where grid reliability is poor and diesel supply chains are challenging."
        ],
        callout: {
          title: "Healthcare Solar Solutions",
          text: "We design custom solar + battery systems for hospitals, clinics, and healthcare facilities. Our systems are engineered for zero-interruption power delivery. Contact us for a healthcare-specific consultation."
        }
      }
    ]
  },
  "15": {
    sections: [
      {
        heading: "The True Cost of Diesel Generators",
        paragraphs: [
          "Many homes and businesses in Bangladesh rely on diesel generators as backup power during load shedding. While generators seem affordable upfront (BDT 50,000-200,000 for residential models), the total cost of ownership over 10-15 years is staggering when you factor in fuel, maintenance, and replacement costs. Solar energy, despite its higher initial investment, proves dramatically cheaper over its lifetime."
        ]
      },
      {
        heading: "Head-to-Head Cost Comparison",
        paragraphs: [
          "Let's compare a 5kW diesel generator vs a 5kW solar system over 15 years for a typical Dhaka household experiencing 2-3 hours of daily load shedding:"
        ],
        table: {
          headers: ["Cost Category", "Diesel Generator", "Solar System"],
          rows: [
            ["Initial purchase", "BDT 150,000", "BDT 300,000"],
            ["Annual fuel cost", "BDT 120,000", "BDT 0"],
            ["Annual maintenance", "BDT 15,000", "BDT 5,000"],
            ["Replacement (every 5-7 yrs)", "BDT 150,000 × 2", "BDT 0"],
            ["Inverter replacement (yr 12)", "—", "BDT 50,000"],
            ["15-year total cost", "BDT 2,475,000", "BDT 425,000"],
            ["Electricity savings", "BDT 0", "BDT 810,000"],
            ["Net 15-year cost", "BDT 2,475,000", "-BDT 385,000 (profit)"]
          ]
        }
      },
      {
        heading: "Beyond Financial Savings",
        paragraphs: [
          "The advantages of solar over generators extend well beyond cost:"
        ],
        list: [
          "Zero noise: Solar systems operate silently — no more generator rumble disturbing sleep, work, or neighbors",
          "Zero emissions: No toxic exhaust fumes, carbon monoxide risk, or contribution to air pollution",
          "Zero fuel dependency: No diesel procurement, storage, or fuel price volatility",
          "Minimal maintenance: No oil changes, filter replacements, or engine overhauls — just occasional panel cleaning",
          "24/7 operation: Solar generates power all day (not just during outages), reducing your grid electricity bill continuously",
          "Property value: Solar installations increase property value by 3-5%, while generators do not",
          "Reliability: No mechanical failures, starting problems, or fuel contamination issues"
        ]
      },
      {
        heading: "When a Generator Might Still Make Sense",
        paragraphs: [
          "In fairness, generators still have a role in specific scenarios: as backup for businesses requiring 100% uptime where battery costs are prohibitive, for construction sites and temporary installations, or for very large power requirements (above 50kW) where solar roof space is insufficient. However, even in these cases, a hybrid solar + small generator setup typically outperforms a generator-only approach."
        ]
      },
      {
        heading: "Making the Switch",
        paragraphs: [
          "If you currently own a generator, you can start your solar transition immediately. Many customers keep their existing generator as emergency backup while their solar system handles daily power needs. Over time, as solar + battery costs continue declining, the generator can be retired completely."
        ],
        callout: {
          title: "Replace Your Generator with Solar",
          text: "Calculate your exact savings by switching from diesel to solar. Our team will analyze your current generator usage and design a solar system that eliminates fuel costs while providing reliable power. Free consultation available."
        }
      }
    ]
  },
  "16": {
    sections: [
      {
        heading: "What the New Incentive Actually Pays",
        paragraphs: [
          "From 1 September 2026, the Power Division set a new buyback rate for surplus rooftop solar electricity fed into the national grid: Tk 10.50 per unit (kWh), guaranteed for three years to anyone who installs an eligible system in time.",
          "The rate isn't arbitrary. The government capped the generation cost of rooftop solar-with-battery systems at Tk 8 per unit based on current market prices and recent tenders, then added a 20% profit margin plus an 11.25% premium — landing on Tk 10.50. For comparison, the average retail grid tariff is currently around Tk 10.40 per unit, so exporting surplus power is now genuinely more attractive than simply offsetting your own bill."
        ]
      },
      {
        heading: "Who Qualifies and the Deadline That Matters",
        paragraphs: [
          "Eligibility runs through the Net Metering Guidelines 2025. To lock in the Tk 10.50 rate you need to:"
        ],
        list: [
          "Install a rooftop solar system, ideally with battery storage, by 28 February 2027",
          "Connect it under a net metering agreement so surplus units are measured and fed back to the grid",
          "Use equipment — panels, batteries, inverters, meters — that meets BSTI and SREDA technical standards",
          "Be a residential or commercial consumer (both qualify)"
        ]
      },
      {
        heading: "Why This Rate Exists Right Now",
        paragraphs: [
          "Bangladesh went through its worst power shortages in years in August 2026, with shortfalls reaching close to 4,000 MW at peak — driven by tight natural gas supply and fuel-price uncertainty tied to wider Middle East instability. Rooftop solar is one of the fastest ways to add generation capacity without needing large tracts of land, which matters in one of the world's most densely populated countries.",
          "The government's broader target is 5,500 MW of rooftop capacity, with rooftop solar potentially covering up to 35% of national electricity demand over time. Right now the country is still early in that curve, so this incentive window is designed to pull adoption forward fast."
        ]
      },
      {
        heading: "How the Payout Works",
        paragraphs: [
          "Your return comes from two places: self-consumption (every unit you use from your own panels replaces grid electricity you'd otherwise pay full retail price for) and surplus export (extra units sold at Tk 10.50 for three years). A well-sited 5 kW system in Bangladesh typically produces 6,000–7,500 units a year — how much of that becomes exportable surplus depends on your daytime usage pattern.",
          "Payments are made directly to your bank account or mobile financial service account, not in cash, and are calculated and transferred by your distribution company."
        ],
        table: {
          headers: ["Item", "Detail"],
          rows: [
            ["Incentive start", "1 September 2026"],
            ["Installation deadline to qualify", "28 February 2027"],
            ["Incentive end date", "28 February 2030 (3 years from install)"],
            ["Payment method", "Bank transfer or mobile financial service"],
            ["Required standards", "BSTI + SREDA approved equipment"]
          ]
        }
      },
      {
        heading: "One Thing to Get Clarified Before You Sign a Contract",
        paragraphs: [
          "Some official statements have referenced a slightly different figure — Tk 10.15 per unit tied to a shorter six-month installation window — as part of related remarks on rooftop solar incentives. The Tk 10.50 / 28 February 2027 structure is the one detailed in the Power Division's gazette notification and reported consistently by major outlets, but if you're weighing a purchase, it's worth asking your installer or a One-Stop Service Centre to confirm in writing exactly which rate and deadline applies to your specific connection before you commit."
        ]
      },
      {
        heading: "Quality Still Decides Whether the Investment Pays Off",
        paragraphs: [
          "An attractive buyback rate doesn't fix a poorly built system. Bangladesh's own experience with older solar home systems is a caution here — a large share stopped working properly within a few years, mostly due to battery failure and lack of maintenance, not the incentive structure. The rate makes a good system more profitable; it doesn't make a bad one reliable."
        ],
        callout: {
          title: "Lock In the Tk 10.50 Rate Before the Deadline",
          text: "The window to qualify closes 28 February 2027. Get a free site survey and a written quote that spells out equipment standards, net metering support, and warranty terms before you decide."
        }
      }
    ]
  },
  "17": {
    sections: [
      {
        heading: "What Solar Actually Costs in Bangladesh Right Now",
        paragraphs: [
          "Prices have kept easing through 2026 on the back of lower import duties and more competition among installers. Here's a realistic range for quality installations at each common system size, based on current market rates."
        ]
      },
      {
        heading: "2026 Price Ranges by System Size",
        paragraphs: [
          "Actual price depends heavily on panel brand, inverter type, and whether you add battery storage — the table below gives typical ranges, not a fixed quote."
        ],
        table: {
          headers: ["System Size", "Type", "Approx. Price (BDT)", "Best For", "Est. Monthly Savings"],
          rows: [
            ["1–2 kW", "Grid-tied / Basic", "85,000 – 180,000", "Small apartments, shops", "1,500 – 3,000"],
            ["3 kW", "Grid-tied / Hybrid", "180,000 – 320,000", "Medium homes", "3,000 – 5,000"],
            ["5 kW", "Hybrid (most popular)", "275,000 – 420,000", "Family homes + light AC", "4,500 – 7,500"],
            ["8–10 kW", "Hybrid", "500,000 – 850,000+", "Large homes, small offices", "8,000 – 14,000"],
            ["20 kW+", "Commercial", "Custom (Tk 75–110/watt)", "Factories, offices, schools", "Significant"]
          ]
        }
      },
      {
        heading: "What Actually Moves the Price",
        paragraphs: [
          "Five factors explain almost all of the spread you'll see between quotes for the same system size:"
        ],
        list: [
          "Panel quality: Tier-1 brands (Trina, JA Solar, REC, Longi) cost more but come with 25-year performance warranties and better real-world efficiency",
          "Inverter type: hybrid inverters that support battery backup cost more than simple grid-tied inverters",
          "Battery storage: lithium (LiFePO4) batteries add meaningfully to upfront cost but are what actually gets you through load shedding",
          "Mounting structure: flat concrete roofs are cheapest to mount on; tin or structurally complex roofs add labor cost",
          "Installation and net metering paperwork: usually bundled into package pricing from reputable installers — confirm this in writing"
        ]
      },
      {
        heading: "A 5 kW System, Concretely",
        paragraphs: [
          "A quality 5 kW hybrid system currently starts around BDT 275,000 and typically includes Tier-1 monocrystalline panels, a hybrid inverter, mounting structure, wiring and protection, net metering support, and installation. With correct sizing and the new Tk 10.50 surplus power incentive, payback periods of 3–4.5 years are realistic for many households."
        ]
      },
      {
        heading: "What You Can Expect to Save",
        paragraphs: [
          "A 5 kW system in a reasonably sunny, unshaded location generates roughly 6,000–7,500 units per year. Between self-consumption and surplus export under the new incentive, many households see electricity bills fall 60–80%. Add battery storage and you also get protection against load shedding, which is a separate (non-financial) benefit worth weighing."
        ]
      },
      {
        heading: "Getting a Quote You Can Actually Trust",
        paragraphs: [
          "Prices above are market ranges, not your price. Your real cost depends on roof condition, shading, electricity usage pattern, and whether you want battery backup."
        ],
        list: [
          "Ask for an itemized quotation, not a single lump-sum number",
          "Prefer Tier-1 panels and reputable hybrid inverter brands",
          "Check warranty terms carefully — panels 25 years, inverter 5–10 years, lithium batteries 5–10 years",
          "Get a free site survey — roof condition and shading materially affect real output",
          "If you want the Tk 10.50 incentive, install before 28 February 2027"
        ],
        callout: {
          title: "Get an Accurate, Site-Specific Quote",
          text: "Contact us for a free site survey and customized quotation based on your actual roof, electricity usage, and whether you want battery backup. We serve customers across Bangladesh."
        }
      }
    ]
  },
  "18": {
    sections: [
      {
        heading: "A Survey That's Worth Taking Seriously",
        paragraphs: [
          "A survey by the Centre for Policy Dialogue (CPD), reported with Samakal, found that roughly 47% of Solar Home Systems (SHS) in Bangladesh are no longer functioning properly. That's not a small footnote — it represents a lot of households who spent real money on solar and ended up with a system that quietly stopped working within a few years.",
          "Understanding why systems fail is the first step to not becoming part of that statistic."
        ]
      },
      {
        heading: "Why Systems Actually Fail",
        paragraphs: [
          "Field reports and the survey point to a consistent set of causes, with one factor dominating the rest."
        ],
        table: {
          headers: ["Rank", "Cause", "Approx. Share", "What's Actually Happening"],
          rows: [
            ["1", "Battery failure", "77%", "The single most common failure point — batteries degrade or die earlier than expected"],
            ["2", "Lack of maintenance", "Very high", "Dust buildup, loose connections, general neglect reduce output over time"],
            ["3", "Poor quality equipment", "Significant", "Low-grade panels, inverters, and charge controllers wear out fast"],
            ["4", "Lightning and weather damage", "14%", "Common where systems lack proper surge and lightning protection"],
            ["5", "No after-sales support", "High", "Installers disappear after the sale, leaving no one to call when something breaks"],
            ["6", "Grid expansion", "Common", "Some households simply stop maintaining SHS once grid power reaches them"]
          ]
        }
      },
      {
        heading: "Batteries Are the Weak Link — Here's Why",
        paragraphs: [
          "Most older solar home systems used lead-acid batteries with a realistic working life of 3–5 years under regular use. Once that battery dies, many owners can't afford — or can't find — a proper replacement, and the whole system effectively becomes useless even though the panels themselves may still be fine.",
          "Modern lithium (LiFePO4) batteries last considerably longer, typically 8–15 years, at a higher upfront cost. That upfront cost buys you a system far less likely to become a stranded asset after a few years."
        ]
      },
      {
        heading: "What the Failed Systems Have in Common",
        paragraphs: [
          "A few patterns show up repeatedly among systems that stopped working:"
        ],
        list: [
          "Free or very cheap systems tended to use the lowest-quality available components",
          "Little to no monitoring or maintenance plan was ever put in place",
          "Owners received minimal training on basic care — panel cleaning, checking connections",
          "After-sales service networks largely collapsed as the older SHS market declined"
        ]
      },
      {
        heading: "How to Choose a System That Actually Lasts",
        paragraphs: [
          "None of this means solar is unreliable — it means quality and service matter more than the sticker price. Six things worth insisting on:"
        ],
        list: [
          "Prioritize quality over the lowest price — look for Tier-1 panels with a 25-year performance warranty",
          "Choose a reputable hybrid inverter brand with local service support",
          "If you need backup during load shedding, invest in a quality lithium battery rather than the cheapest lead-acid option",
          "Demand proper installation and documentation — correct mounting, earthing, lightning protection, and net metering paperwork",
          "Choose an installer that actually offers after-sales support — ask about warranty claim process, response time, and whether they have local technicians",
          "Plan for basic maintenance — an annual check-up and periodic panel cleaning prevents most avoidable failures"
        ]
      },
      {
        heading: "The Encouraging Part",
        paragraphs: [
          "System quality has genuinely improved. Better panels, hybrid inverters, and lithium batteries are more widely available in 2026 than they were during the older SHS boom, and government incentives — including the new Tk 10.50 surplus power rate — make higher-quality systems more financially attractive than they used to be. A solar system installed properly today should still be producing well after 20+ years, not failing in 4–5."
        ],
        callout: {
          title: "Want a System Designed to Last?",
          text: "We use Tier-1 panels and focus on long-term performance and after-sales support. Get a free site survey and an honest recommendation based on your actual needs and budget."
        }
      }
    ]
  }
};
