// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjgnptivvbxtdqueszkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqZ25wdGl2dmJ4dGRxdWVzemtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDkxNTgsImV4cCI6MjA2NTU4NTE1OH0.RlLOJSXZzlumqYGnUSWF1saM0Vo8roYw8S0UuBRP7TM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);